### ISSUE TITLE
Crawling section: How's the pacing?

### ISSUE THREAD

**Issue by keithjgrant** [keithjgrant/Taming-CSS#4]
I've crammed a lot into these early chapters.  I'm especially curious how folks new to CSS feel about this.  Do I need more examples?  Should I speed up or slow down any?  Let me know what you think!

**Comment by alexanderklein** [comment]
Hi Keith,
I've read through the available chapters and agree that this is probably going to be the best resource to really understand CSS. I'm not entirely new to this topic and was already familiar with these basic concepts. But I still learned something new. I.e. your explanation about specifity is really great and I already re-used it just yesterday when I had a discussion with one of my web engineers :-) 
The pace and the amount of examples seem ideal to me and I really hope that you will be able to complete this invaluable work. I would definitely purchase a printed copy if you reach this stage.

One thing: I think there is a potentially critical typo in one of your code examples:
https://github.com/keithjgrant/Taming-CSS/blob/master/Crawling/chapter3.md#working-with-the-cascade

Your are referencing "nav" as a class, but it is an ID in the HTML code. You introduce the class a little later but I'm pretty sure that you intended referring to the ID in this particular piece of code.

Thanks again for your work, Alex

**Comment by keithjgrant** [comment]
Good catch on that typo, thanks.

Thanks for the feedback. I'm glad you're enjoying so far.  I will definitely see this through to the end.  Not a lot of activity on the repo this week, as I've been working on bigger picture a bit, reworking the outline & doing some research--but I'm definitely still at it :)
