### ISSUE TITLE
Hi, I read your post Against CSS in JS

### ISSUE THREAD

**Issue by victor871129** [keithjgrant/Taming-CSS#7]
Are you aware of this method?
https://github.com/rstacruz/rscss

**Comment by keithjgrant** [comment]
Hi, thanks, that's a good find. That looks very similar to my favorite methodology, SMACSS (https://smacss.com/), with some slightly different naming conventions.  I'll have to keep an eye on it.

**Comment by stramel** [comment]
@victor871129 Which post are you referring to? 

So many of those articles out there with preference on conventions. BEM/SMACSS/ITCSS etc.

**Comment by keithjgrant** [comment]
He's referring to this one on my site: http://keithjgrant.com/posts/against-css-in-js.html

It's in response some trends in the ReactJS world.
